"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$python\
$character"""

palette = "serendipity_midnight"

[palettes.serendipity_midnight]
bg_dark      = "#1C1E2D"
fg_light     = "#DEE0EF"
gold         = "#F8D2C9"
blue         = "#5BA2D0"
purple       = "#A78BFA"
cyan         = "#9CCFD8"
orange       = "#EE8679"
muted        = "#8D8F9E"
accent       = "#94B8FF"

[os]
format = "$symbol"
disabled = false

[os.symbols]
Alpine = 'ïŒ€'
Amazon = 'ï‰°'
Android = 'îœ'
Arch = 'ó°£‡'
CentOS = 'ïŒ„'
Debian = 'ïŒ†'
EndeavourOS = 'ïŒ¢'
Fedora = 'ïŒŠ'
FreeBSD = 'ïŒŒ'
Garuda = 'ï…¼'
Gentoo = 'ïŒ'
Linux = 'ï…¼'
Macos = 'ïŒ‚'
Manjaro = 'ïŒ’'
Mariner = 'ï…¼'
Mint = 'ïŒ'
NetBSD = 'ï…¼'
NixOS = 'ïŒ“'
OpenBSD = 'ïŒ¨'
OpenCloudOS = 'î®ª'
openEuler = 'ï…¼'
openSUSE = 'ïŒ”'
OracleLinux = 'âŠ‚âŠƒ'
Pop = 'ïŒª'
Raspbian = 'ïŒ•'
Redhat = 'ïŒ–'
RedHatEnterprise = 'ïŒ–'
Solus = 'ïŒ­'
SUSE = 'ïŒ”'
Ubuntu = 'ïŒ›'
Unknown = 'ï„ˆ'
Windows = 'îœ'

[character]
success_symbol = "[â”€â¯](fg:blue)"
error_symbol = "[â”€Ã—](fg:orange)"

[directory]
format = "[î‚¶](fg:bg_dark)[$path]($style)[î‚´ ](fg:bg_dark)"
style = "fg:gold bg:bg_dark"

[username]
style_user = "fg:muted"
show_always = true

[time]
format = "[$time](fg:gold)"
time_format = "%a, %I:%M %p"
disabled = true

[git_branch]
format = "[ $symbol $branch ]($style) "
symbol = "îœ¥"
style = "fg:cyan"

[git_state]
style = "fg:purple"
format = "[$state( $progress_current/$progress_total )]($style)"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "fg:orange"

[cmd_duration]
style = "fg:purple"
format = "â± [$duration]($style) "

[python]
format = "via [ğŸ $virtualenv]($style) "
style = "fg:blue"
symbol = "ğŸ "
disabled = false

